### ISSUE TITLE
Update images for Collaboratory homepage

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/open-collaboratory#100]
please find needed images here: https://drive.google.com/drive/u/0/folders/1_MEmQKLoKbG9lB-spqgAtBQSKtWr3MoX

This is a MUST HAVE! 

@litenull - Please update these images as I am unable to see the needed field in the CMS.

**Comment by colleenskemp** [comment]
@litenull - It is not clear to me how to update these fro the content manager. 

Here are the steps I took: 
From CMS main page, I selected: Pages > Home 
https://deploy-preview-69--modest-roentgen-e63e0e.netlify.app/admin/#/collections/pages/entries/home

I can see the following fields: 
Title, Description, Links and Projects. I don't see where I can go to update the images. 

I'm also unable to make the change from the media assets tab. 

@litenull - Since I am blocked here, **please make these needed updates prior to the client walk-through on Monday!** Update the second image to water and the third image to the land image found here: https://drive.google.com/drive/u/0/folders/1_MEmQKLoKbG9lB-spqgAtBQSKtWr3MoX

I will create a related ticket for the footer update. THIS IS A P1! Thank you!

**Comment by litenull** [comment]
Hey @colleenskemp you're on the wrong URL.

See https://modest-roentgen-e63e0e.netlify.app/

**Comment by litenull** [comment]
Hey @colleenskemp you're on the wrong URL.

See https://modest-roentgen-e63e0e.netlify.app/
