### ISSUE TITLE
As a collaborator, I can submit resources

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/open-collaboratory#14]
Submit a resource link should take a user to the CMS page for creating a new resource item. Resources should be associated with one or more projects, and have a title, description, link, and file field. Title and description are required.

**Comment by shrutimehta13** [comment]
Add/edit resource works from the cms https://deploy-preview-69--modest-roentgen-e63e0e.netlify.app/admin/#/collections/resources

Integration with Project will be tested in #64.
