### ISSUE TITLE
Issue with resources display on Project detail page

### ISSUE THREAD

**Issue by shrutimehta13** [ProjectDrawdown/open-collaboratory#195]
As per design-
 1. we should not be showing name and desc
2. resource link should appear as a hover link (hyperlink)
TBD- how should a file uploaded to resource display . @ralphcutler design guidance please 

<img width="1055" alt="Screenshot 2021-10-27 at 11 30 48 AM" src="https://user-images.githubusercontent.com/34771314/139008686-5f3259b9-2dd2-447d-8cb9-fa5ea01eb59d.png">

**Comment by colleenskemp** [comment]
There may be some deviation from design here. Closing this ticket. Captured in parallel ticket #39
