### ISSUE TITLE
unpublished action removing entry from Admin (not visible for later edits)

### ISSUE THREAD

**Issue by shrutimehta13** [ProjectDrawdown/open-collaboratory#202]
1. Go to Admin https://modest-roentgen-e63e0e.netlify.app/admin/#/collections/projects
and Create a project > publish

observed:Project visble on site https://modest-roentgen-e63e0e.netlify.app/projects

2. in  Admin, choose to unpublish
<img width="1044" alt="Screenshot 2021-10-27 at 12 15 35 PM" src="https://user-images.githubusercontent.com/34771314/139014357-4dbc90c2-89d5-45a9-841b-cb613c15d08b.png">

observed: entry removed from display on site. also wrongly removed from admin. Unable to recover and make changes.

**Comment by colleenskemp** [comment]
Unpublished projects should remain as draft

**Comment by litenull** [comment]
Thats how the CMS works. I dont think we can make changes to this.

**Comment by colleenskemp** [comment]
A PR is opened and has to be manually re-merged. Once re-merged, project will appear in CMS.
