### ISSUE TITLE
Navigation Issues

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/open-collaboratory#228]
As a user, when i navigate to the project detail page 
I cannot go back to the homepage without first going to the project listing page. 

Request: User should be able to navigate directly to homepage from project detail through on site navigation.

**Comment by colleenskemp** [comment]
@eethann suggestion in slack to implement breadcrumbs: 
https://colab-coop.slack.com/archives/G01ANEKHCQP/p1635778633071200

Home > Projects > Project Name

**Comment by ralphcutler** [comment]
Sounds like breadcrumbs are not supported. My suggestion would hopefully require minor changes. We can move the back link section to the top, above the the heading and add an evergreen "home" link. This would be on all interior template pages.  

![2021-11-01 at 11 20 AM](https://user-images.githubusercontent.com/9847479/139705101-bdf521c8-fdc0-401e-8b57-cc461aece824.jpg)
https://www.figma.com/file/hqCFFKf4aiA9An0yQsQilU/Collaboratory-(Chakra-UI-Figma-Kit)?node-id=959%3A9265
