### ISSUE TITLE
Users can return to homepage from anywhere by clicking on header navigation

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/open-collaboratory#246]
Acceptance criteria: Users can return to homepage from anywhere by clicking on header navigation. 

@ralph & @litenull  - Will you please connect on design direction for this navigation improvement. The conversation we had with Chad today was going in the direction of an icon or project name treatment "Drawdown Research Platform" which when clicked from the header brings users back to homepage 

Here is what @ralphcutler shared previously. Can you please workshop this together? 
![navigation imrpovement suggestion](https://user-images.githubusercontent.com/20732309/140194681-fe96efd1-5a2c-489a-9c53-1c278b5daa7b.jpeg)

**Comment by colleenskemp** [comment]
This is a duplicate replacing #228

**Comment by ralphcutler** [comment]
I get what you are saying as far as direction. In this context Icon = Logo really. We could use a house I guess. That could be cool. The words 'Drawdown Research Platform ' in this postition would not necessarily be clear as to where that link goes

**Comment by colleenskemp** [comment]
We can use the home icon. For project listing, you can use steps.

**Comment by colleenskemp** [comment]
@litenull - We don't see any changes here. Please take another pass. Let @ralphcutler know if you need help or further direction/ support.

**Comment by ralphcutler** [comment]
Putting this here for future use: https://react-icons.github.io/react-icons/search?q=home
