### ISSUE TITLE
Logos on homepage are scaled to display at the same size

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/open-collaboratory#261]
This is a request coming out of client QA. Please scale to logos so that they all appear at a consistent size. 

Here is the current state: 
<img width="1280" alt="Screen Shot 2021-11-07 at 11 13 38 AM" src="https://user-images.githubusercontent.com/20732309/140654814-7c0e5ed2-15b3-4814-ba72-9693ebe25607.png">

**Comment by litenull** [comment]
I wasnt able to get this to work. @brodavi Help!
