### ISSUE TITLE
Styling - Project Detail Page

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/open-collaboratory#39]
Time estimate: @tomaz please communicate a time estimate in the comments. 

Acceptance criterial: The project detail page must contain the following elements: 
- Project Title
- Project link
- The ability for an admin to embed a youtube video (this is a big blank space in the image below. Some problem when exporting the file). 
- Description
- Contributors section
- A section linking to associated resources in resource library
- Styling should match this design: https://www.figma.com/file/hqCFFKf4aiA9An0yQsQilU/Collaboratory-Chakra-UI-Figma-Kit?node-id=959%3A9265

The only design element which is still unclear is where the active project tag appears on this page. 
![Project Detail Page](https://user-images.githubusercontent.com/20732309/134065868-d4701514-7874-42cc-99db-4adeadfac615.png)

**Comment by colleenskemp** [comment]
@ralphcutler - I have 2 questions for you on this design: 
1) Where is the active identifier? Should that appear here somewhere? 
2) Where does the project link take me? Does it bring me to the associated resource? + @eethann

**Comment by colleenskemp** [comment]
There are multiple issues still present which need another pass. Generally, please refer to @ralphcutler's mark-up in the above comments. I am just drawing issues still clear to me from that overview. 

1. Font weight issues. The font and weight for the descriptive text is not correct. Still need to install "normal" font weight. Please review design and revise
2. For page title, please install extra bold font weight. 
3. There are spacing adjustments needed. For example, insufficient space between video and description. Please review design and update spacing throughout. 
4. Color for the project link has not been corrected
5. The description for the hub resources: text should be "normal" and link should be in blue clickable text. 

@brodavi - Could you help with this? @Chukslord1 will be out this week and this is something that we should have ready for Monday.

**Comment by brodavi** [comment]
PR https://github.com/ProjectDrawdown/open-collaboratory/pull/219

**Comment by colleenskemp** [comment]
@shrutimehta13 - Will you take the final pass at testing this?

**Comment by shrutimehta13** [comment]
Close to the design but Fontsize, weight have variations from design for **all** headings/text. eg project name should be 24px/600 instead of 30px/700

**Comment by colleenskemp** [comment]
Significant improvement here. We are good with where we are.
