### ISSUE TITLE
Integrate resources to the project detail page

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/open-collaboratory#64]
Integrate the resource from the admin to the project detail page. Show the resources at the bottom of the project detail page.

Design reference link: https://www.figma.com/file/hqCFFKf4aiA9An0yQsQilU/Collaboratory-Chakra-UI-Figma-Kit?node-id=841%3A9582

Acceptance criteria: Resources associated with the project display at the bottom of the page.

**Comment by brodavi** [comment]
PR @litenull https://github.com/ProjectDrawdown/open-collaboratory/pull/66
