### ISSUE TITLE
Testing at different screen sizes

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/open-collaboratory#74]
Will you please test how this looks for common breakpoints at small, medium, and large sizes? 

Quicklink to app: https://modest-roentgen-e63e0e.netlify.app/

Please review the following screens: 
- landing page
- project browse
- project detail page

You will see design comps providing direction on different screen sizes here: https://www.figma.com/file/hqCFFKf4aiA9An0yQsQilU/Collaboratory-Chakra-UI-Figma-Kit?node-id=0%3A1

**Comment by colleenskemp** [comment]
@shrutimehta13 - Mobile isn't yet ready to test.

**Comment by shrutimehta13** [comment]
@colleenskemp I see the ticket #49 closed. Please confirm expectation for this ticket closure .
Do we need to test on mobile?  I see couple of issues for eg--
1. homepage and project detail page does not fit on mobile
![IMG_5EC8C79367B4-1](https://user-images.githubusercontent.com/34771314/142904357-5361c4a5-afa3-4f89-9243-06bb49cf2180.jpeg)
![IMG_56B40B47FF6D-1](https://user-images.githubusercontent.com/34771314/142904399-2ecac042-1287-4224-af91-8c101556c856.jpeg)
2. footer trunncated- copyright/product name not visible
![IMG_AD02C436337D-1](https://user-images.githubusercontent.com/34771314/142904671-45e34c78-40c1-47a0-98bc-21605dab57ae.jpeg)
3. project listing page is too cramped. 
-some text like search helper text appears too big 
- Active appears bigger than project name
![IMG_41F7D5DAF2C7-1](https://user-images.githubusercontent.com/34771314/142905015-07139e8a-ac82-4222-8bfd-95e160eb105d.jpeg)
4. any video link appears full screen portrait view ie truncates
![IMG_608E71F6C3D0-1](https://user-images.githubusercontent.com/34771314/142905026-e8f59b98-f05c-4b69-ba9e-de63d6dc1f03.jpeg)
5. Project detail page top stacking of links look confusing. Should think of repositioning Collaborate
![IMG_7064](https://user-images.githubusercontent.com/34771314/142905438-7645fa9a-5658-469e-b527-444de9e5a5af.jpg)

**Comment by colleenskemp** [comment]
Issues created from your feedback @shrutimehta13 - 
1. 
2. Footer truncated. Copyright/product name not visible. #423

**Comment by shrutimehta13** [comment]
Good to close.  All issues logged. 
4. Ok after play. Issue was with cover image on play
