### ISSUE TITLE
As a user, I can access a sneak peek of in progress web UI and python solution

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/open-collaboratory#98]
Description: 
It was one of the initial requirements of this site that it provide access to the other critical work that we are doing. 

Please provide a UX/ design that enables user to - 

- Follow a link to view the Drawdown Global Research Platform Web UI repo
- Follow a link to view the Drawdown solutions in python repo

Language recommended by client: 
"see a sneak peek" "software under development"

**Comment by ralphcutler** [comment]
@colleenskemp Can you share the 2 links? Are they github projects?
